// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseSavefile(arg1) {
  return window['go']['main']['App']['ParseSavefile'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ProcessSaveData(arg1) {
  return window['go']['main']['App']['ProcessSaveData'](arg1);
}

export function SelectAndSyncGarage() {
  return window['go']['main']['App']['SelectAndSyncGarage']();
}

export function TestMatchmaker(arg1, arg2) {
  return window['go']['main']['App']['TestMatchmaker'](arg1, arg2);
}
