// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ParseSavefile(arg1:string):Promise<Array<backend.ACLoadout>>;

export function Ping():Promise<string>;

export function ProcessSaveData(arg1:string):Promise<Array<backend.ACLoadout>>;

export function SelectAndSyncGarage():Promise<Array<backend.ACLoadout>>;

export function TestMatchmaker(arg1:backend.ACLoadout,arg2:backend.ACLoadout):Promise<void>;
