// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommissioner(arg1) {
  return window['go']['main']['App']['AddCommissioner'](arg1);
}

export function CaptureACPreview() {
  return window['go']['main']['App']['CaptureACPreview']();
}

export function ExportColorSave(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportColorSave'](arg1, arg2, arg3, arg4);
}

export function IsCommissioner(arg1) {
  return window['go']['main']['App']['IsCommissioner'](arg1);
}

export function ParseApolloExport() {
  return window['go']['main']['App']['ParseApolloExport']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ProcessSaveData(arg1, arg2) {
  return window['go']['main']['App']['ProcessSaveData'](arg1, arg2);
}

export function RemoveCommissioner(arg1) {
  return window['go']['main']['App']['RemoveCommissioner'](arg1);
}

export function TestMatchmaker(arg1, arg2) {
  return window['go']['main']['App']['TestMatchmaker'](arg1, arg2);
}

export function TileSpectatorWindows() {
  return window['go']['main']['App']['TileSpectatorWindows']();
}

export function GetAppMode() {
  return window['go']['main']['App']['GetAppMode']();
}
