// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddCommissioner(arg1:string):Promise<void>;

export function CaptureACPreview():Promise<string>;

export function ExportColorSave(arg1:string,arg2:backend.PPSTColorScheme,arg3:backend.PPSTColorScheme,arg4:number):Promise<void>;

export function IsCommissioner(arg1:string):Promise<boolean>;

export function ParseApolloExport():Promise<Array<backend.ACLoadout>>;

export function Ping():Promise<string>;

export function ProcessSaveData(arg1:string,arg2:string):Promise<Array<backend.ACLoadout>>;

export function RemoveCommissioner(arg1:string):Promise<void>;

export function TestMatchmaker(arg1:backend.ACLoadout,arg2:backend.ACLoadout):Promise<void>;

export function TileSpectatorWindows():Promise<string>;
